### ISSUE TITLE
createSimpleProduct() requires basic-auth plugin installed

### ISSUE THREAD

**Issue by BrianHenryIE** [woocommerce/woocommerce-e2e-boilerplate#9]
It would be nice to have the [Basic Auth plugin](https://github.com/WP-API/Basic-Auth) installed by default. `createSimpleProduct()` doesn't work until it is installed, and I assume other functions too.

Adding this to `tests/e2e/docker/initialize.sh` should do the job:
```
wp plugin install https://github.com/WP-API/basic-auth/archive/master.zip --activate
```

Error output:
```
npx wc-e2e test:e2e
Testing URL: http://localhost:8084

  console.error
    Failed to load resource: the server responded with a status of 404 (Not Found)

      at Page.<anonymous> (../../../../../../ronrennick/Sites/solaris/woocommerce/tests/e2e/env/src/setup/jest.setup.js:182:3)
      at Page._onLogEntryAdded (../../puppeteer/lib/Page.js:224:12)
      at CDPSession.<anonymous> (../../puppeteer/lib/Page.js:124:47)
      at CDPSession._onMessage (../../puppeteer/lib/Connection.js:200:12)
      at Connection._onMessage (../../puppeteer/lib/Connection.js:112:17)

 FAIL  ../../../tests/e2e/specs/blacklist-address.test.js (5.897s)
  BlacklistsTests
    ✕ should block any address with zip code 94107 (939ms)

  * BlacklistsTests › should block any address with zip code 94107

    Failed: HTTPResponse {
      "data": Object {
        "code": "woocommerce_rest_cannot_create",
        "data": Object {
          "status": 401,
        },
        "message": "Sorry, you are not allowed to create resources.",
      },
      "headers": Object {
        "access-control-allow-headers": "Authorization, X-WP-Nonce, Content-Disposition, Content-MD5, Content-Type",
        "access-control-expose-headers": "X-WP-Total, X-WP-TotalPages, Link",
        "connection": "close",
        "content-length": "123",
        "content-type": "application/json; charset=UTF-8",
        "date": "Thu, 08 Jul 2021 20:26:30 GMT",
        "link": "<http://localhost:8084/index.php?rest_route=/>; rel=\"https://api.w.org/\"",
        "server": "Apache/2.4.38 (Debian)",
        "x-content-type-options": "nosniff",
        "x-powered-by": "PHP/7.4.12",
        "x-robots-tag": "noindex",
      },
      "statusCode": 401,
    }

      28 | // const runBlacklistTest = () => {
      29 |     describe('BlacklistsTests', () => {
    > 30 |         beforeAll(async () => {
         |         ^
      31 |
      32 |             // activate plugin.
      33 |

      at Env.beforeAll (node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:41:24)
      at Suite.<anonymous> (../../../tests/e2e/specs/blacklist-address.test.js:30:9)
      at Object.<anonymous> (../../../tests/e2e/specs/blacklist-address.test.js:29:5)

  * BlacklistsTests › should block any address with zip code 94107

    TypeError: Cannot read property 'click' of undefined

      at _callee3$ (../../../../../../ronrennick/Sites/solaris/woocommerce/tests/e2e/utils/src/flows/shopper.js:48:19)
      at tryCatch (../../regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (../../regenerator-runtime/runtime.js:293:22)
      at Generator.next (../../regenerator-runtime/runtime.js:118:21)
      at asyncGeneratorStep (../../@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (../../@babel/runtime/helpers/asyncToGenerator.js:25:9)

```

**Comment by zhongruige** [comment]
@BrianHenryIE thank you for reporting this! That is a good call out, that change makes sense (as we already do this in the [core e2e tests docker environment](https://github.com/woocommerce/woocommerce/blob/trunk/tests/e2e/docker/initialize.sh#L14)), so we should also make that update here.

**Comment by rrennick** [comment]
Created https://github.com/woocommerce/woocommerce/issues/30280 as well.
